# Generated by Django 3.1.2 on 2020-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201009_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
