# Generated by Django 3.1.2 on 2020-10-13 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20201013_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Followed_by',
            field=models.ManyToManyField(related_name='Followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
