# Generated by Django 3.1.2 on 2020-10-13 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20201013_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Followed_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
