# Generated by Django 3.1.2 on 2020-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201013_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, to='network.Post'),
        ),
    ]
