# Generated by Django 3.1.2 on 2020-10-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20201015_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follower',
            new_name='followers',
        ),
    ]
