# Generated by Django 3.1.2 on 2020-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0035_auto_20201014_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
