# Generated by Django 3.1.2 on 2020-10-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_auto_20201014_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followed_by',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
