# Generated by Django 3.1.2 on 2020-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0039_auto_20201014_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
